# Generated by Django 4.2.5 on 2023-10-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To do', 'TO DO'), ('In progress', 'IN PROGRESS')], max_length=100),
        ),
    ]
